export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST ";
export const GET_CONVERSATION_SUCESS = "GET_CONVERSATION_SUCESS ";
export const GET_CONVERSATION_FAIL = "GET_CONVERSATION_FAIL ";

export const FRIEND_CONVERSATION_REQUEST = "FRIEND_CONVERSATION_REQUEST ";
export const FRIEND_CONVERSATION_SUCESS = "FRIEND_CONVERSATION_SUCESS ";
export const FRIEND_CONVERSATION_FAIL = "FRIEND_CONVERSATION_FAIL ";

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST ";
export const CREATE_CONVERSATION_SUCESS = "CREATE_CONVERSATION_SUCESS ";
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL ";
export const CREATE_CONVERSATION_RESET = "CREATE_CONVERSATION_RESET ";

export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const SET_CURRENT_MESSANGER = "SET_CURRENT_MESSANGER";
export const MSG_ACTIVE = "MSG_ACTIVE";
export const MSG_NOT_ACTIVE = "MSG_NOT_ACTIVE";
