export const SINGLE_POST_REQUEST = "SINGLE_POST_REQUEST ";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS ";
export const SINGLE_POST_FAIL = "SINGLE_POST_FAIL";

export const TIMELINE_POST_REQUEST = "TIMELINE_POST_REQUEST ";
export const TIMELINE_POST_SUCCESS = "TIMELINE_POST_SUCCESS ";
export const TIMELINE_POST_FAIL = "TIMELINE_POST_FAIL";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST ";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS ";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST ";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS ";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const ONE_POST_REQUEST = "ONE_POST_REQUEST ";
export const ONE_POST_SUCCESS = "ONE_POST_SUCCESS ";
export const ONE_POST_FAIL = "ONE_POST_FAIL";
export const ONE_POST_RESET = " ONE_POST_RESET";

export const POST_CREATE_REVIEW_REQUEST = "POST_CREATE_REVIEW_REQUEST";
export const POST_CREATE_REVIEW_SUCCESS = "POST_CREATE_REVIEW_SUCCESS";
export const POST_CREATE_REVIEW_FAIL = "POST_CREATE_REVIEW_FAIL";
export const POST_CREATE_REVIEW_RESET = "POST_CREATE_REVIEW_RESET";
